# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/greg/fuchsia/mojo/examples/emudore

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/greg/fuchsia/mojo/examples/emudore

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/greg/fuchsia/mojo/examples/emudore/CMakeFiles /home/greg/fuchsia/mojo/examples/emudore/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/greg/fuchsia/mojo/examples/emudore/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named emudore

# Build rule for target.
emudore: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 emudore
.PHONY : emudore

# fast build rule for target.
emudore/fast:
	$(MAKE) -f CMakeFiles/emudore.dir/build.make CMakeFiles/emudore.dir/build
.PHONY : emudore/fast

src/c64.o: src/c64.cpp.o

.PHONY : src/c64.o

# target to build an object file
src/c64.cpp.o:
	$(MAKE) -f CMakeFiles/emudore.dir/build.make CMakeFiles/emudore.dir/src/c64.cpp.o
.PHONY : src/c64.cpp.o

src/c64.i: src/c64.cpp.i

.PHONY : src/c64.i

# target to preprocess a source file
src/c64.cpp.i:
	$(MAKE) -f CMakeFiles/emudore.dir/build.make CMakeFiles/emudore.dir/src/c64.cpp.i
.PHONY : src/c64.cpp.i

src/c64.s: src/c64.cpp.s

.PHONY : src/c64.s

# target to generate assembly for a file
src/c64.cpp.s:
	$(MAKE) -f CMakeFiles/emudore.dir/build.make CMakeFiles/emudore.dir/src/c64.cpp.s
.PHONY : src/c64.cpp.s

src/cia1.o: src/cia1.cpp.o

.PHONY : src/cia1.o

# target to build an object file
src/cia1.cpp.o:
	$(MAKE) -f CMakeFiles/emudore.dir/build.make CMakeFiles/emudore.dir/src/cia1.cpp.o
.PHONY : src/cia1.cpp.o

src/cia1.i: src/cia1.cpp.i

.PHONY : src/cia1.i

# target to preprocess a source file
src/cia1.cpp.i:
	$(MAKE) -f CMakeFiles/emudore.dir/build.make CMakeFiles/emudore.dir/src/cia1.cpp.i
.PHONY : src/cia1.cpp.i

src/cia1.s: src/cia1.cpp.s

.PHONY : src/cia1.s

# target to generate assembly for a file
src/cia1.cpp.s:
	$(MAKE) -f CMakeFiles/emudore.dir/build.make CMakeFiles/emudore.dir/src/cia1.cpp.s
.PHONY : src/cia1.cpp.s

src/cia2.o: src/cia2.cpp.o

.PHONY : src/cia2.o

# target to build an object file
src/cia2.cpp.o:
	$(MAKE) -f CMakeFiles/emudore.dir/build.make CMakeFiles/emudore.dir/src/cia2.cpp.o
.PHONY : src/cia2.cpp.o

src/cia2.i: src/cia2.cpp.i

.PHONY : src/cia2.i

# target to preprocess a source file
src/cia2.cpp.i:
	$(MAKE) -f CMakeFiles/emudore.dir/build.make CMakeFiles/emudore.dir/src/cia2.cpp.i
.PHONY : src/cia2.cpp.i

src/cia2.s: src/cia2.cpp.s

.PHONY : src/cia2.s

# target to generate assembly for a file
src/cia2.cpp.s:
	$(MAKE) -f CMakeFiles/emudore.dir/build.make CMakeFiles/emudore.dir/src/cia2.cpp.s
.PHONY : src/cia2.cpp.s

src/cpu.o: src/cpu.cpp.o

.PHONY : src/cpu.o

# target to build an object file
src/cpu.cpp.o:
	$(MAKE) -f CMakeFiles/emudore.dir/build.make CMakeFiles/emudore.dir/src/cpu.cpp.o
.PHONY : src/cpu.cpp.o

src/cpu.i: src/cpu.cpp.i

.PHONY : src/cpu.i

# target to preprocess a source file
src/cpu.cpp.i:
	$(MAKE) -f CMakeFiles/emudore.dir/build.make CMakeFiles/emudore.dir/src/cpu.cpp.i
.PHONY : src/cpu.cpp.i

src/cpu.s: src/cpu.cpp.s

.PHONY : src/cpu.s

# target to generate assembly for a file
src/cpu.cpp.s:
	$(MAKE) -f CMakeFiles/emudore.dir/build.make CMakeFiles/emudore.dir/src/cpu.cpp.s
.PHONY : src/cpu.cpp.s

src/io_fuchsia.o: src/io_fuchsia.cpp.o

.PHONY : src/io_fuchsia.o

# target to build an object file
src/io_fuchsia.cpp.o:
	$(MAKE) -f CMakeFiles/emudore.dir/build.make CMakeFiles/emudore.dir/src/io_fuchsia.cpp.o
.PHONY : src/io_fuchsia.cpp.o

src/io_fuchsia.i: src/io_fuchsia.cpp.i

.PHONY : src/io_fuchsia.i

# target to preprocess a source file
src/io_fuchsia.cpp.i:
	$(MAKE) -f CMakeFiles/emudore.dir/build.make CMakeFiles/emudore.dir/src/io_fuchsia.cpp.i
.PHONY : src/io_fuchsia.cpp.i

src/io_fuchsia.s: src/io_fuchsia.cpp.s

.PHONY : src/io_fuchsia.s

# target to generate assembly for a file
src/io_fuchsia.cpp.s:
	$(MAKE) -f CMakeFiles/emudore.dir/build.make CMakeFiles/emudore.dir/src/io_fuchsia.cpp.s
.PHONY : src/io_fuchsia.cpp.s

src/loader.o: src/loader.cpp.o

.PHONY : src/loader.o

# target to build an object file
src/loader.cpp.o:
	$(MAKE) -f CMakeFiles/emudore.dir/build.make CMakeFiles/emudore.dir/src/loader.cpp.o
.PHONY : src/loader.cpp.o

src/loader.i: src/loader.cpp.i

.PHONY : src/loader.i

# target to preprocess a source file
src/loader.cpp.i:
	$(MAKE) -f CMakeFiles/emudore.dir/build.make CMakeFiles/emudore.dir/src/loader.cpp.i
.PHONY : src/loader.cpp.i

src/loader.s: src/loader.cpp.s

.PHONY : src/loader.s

# target to generate assembly for a file
src/loader.cpp.s:
	$(MAKE) -f CMakeFiles/emudore.dir/build.make CMakeFiles/emudore.dir/src/loader.cpp.s
.PHONY : src/loader.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/emudore.dir/build.make CMakeFiles/emudore.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/emudore.dir/build.make CMakeFiles/emudore.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/emudore.dir/build.make CMakeFiles/emudore.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/memory.o: src/memory.cpp.o

.PHONY : src/memory.o

# target to build an object file
src/memory.cpp.o:
	$(MAKE) -f CMakeFiles/emudore.dir/build.make CMakeFiles/emudore.dir/src/memory.cpp.o
.PHONY : src/memory.cpp.o

src/memory.i: src/memory.cpp.i

.PHONY : src/memory.i

# target to preprocess a source file
src/memory.cpp.i:
	$(MAKE) -f CMakeFiles/emudore.dir/build.make CMakeFiles/emudore.dir/src/memory.cpp.i
.PHONY : src/memory.cpp.i

src/memory.s: src/memory.cpp.s

.PHONY : src/memory.s

# target to generate assembly for a file
src/memory.cpp.s:
	$(MAKE) -f CMakeFiles/emudore.dir/build.make CMakeFiles/emudore.dir/src/memory.cpp.s
.PHONY : src/memory.cpp.s

src/vic.o: src/vic.cpp.o

.PHONY : src/vic.o

# target to build an object file
src/vic.cpp.o:
	$(MAKE) -f CMakeFiles/emudore.dir/build.make CMakeFiles/emudore.dir/src/vic.cpp.o
.PHONY : src/vic.cpp.o

src/vic.i: src/vic.cpp.i

.PHONY : src/vic.i

# target to preprocess a source file
src/vic.cpp.i:
	$(MAKE) -f CMakeFiles/emudore.dir/build.make CMakeFiles/emudore.dir/src/vic.cpp.i
.PHONY : src/vic.cpp.i

src/vic.s: src/vic.cpp.s

.PHONY : src/vic.s

# target to generate assembly for a file
src/vic.cpp.s:
	$(MAKE) -f CMakeFiles/emudore.dir/build.make CMakeFiles/emudore.dir/src/vic.cpp.s
.PHONY : src/vic.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... emudore"
	@echo "... src/c64.o"
	@echo "... src/c64.i"
	@echo "... src/c64.s"
	@echo "... src/cia1.o"
	@echo "... src/cia1.i"
	@echo "... src/cia1.s"
	@echo "... src/cia2.o"
	@echo "... src/cia2.i"
	@echo "... src/cia2.s"
	@echo "... src/cpu.o"
	@echo "... src/cpu.i"
	@echo "... src/cpu.s"
	@echo "... src/io_fuchsia.o"
	@echo "... src/io_fuchsia.i"
	@echo "... src/io_fuchsia.s"
	@echo "... src/loader.o"
	@echo "... src/loader.i"
	@echo "... src/loader.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/memory.o"
	@echo "... src/memory.i"
	@echo "... src/memory.s"
	@echo "... src/vic.o"
	@echo "... src/vic.i"
	@echo "... src/vic.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

